apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-06-11T17:01:53Z"
  labels:
    app: bootcamp-k8s
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:ports:
          .: {}
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-expose
    operation: Update
    time: "2021-06-11T17:01:53Z"
  name: bootcamp-k8s
  namespace: bootcamp
  resourceVersion: "19664"
  selfLink: /api/v1/namespaces/bootcamp/services/bootcamp-k8s
  uid: 43947f28-b36d-4f04-987e-ef43ddb96415
spec:
  clusterIP: 10.104.173.219
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: bootcamp-k8s
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
